default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: "^tests/__snapshots__"
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.285"
    hooks:
      - id: ruff

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.324
    hooks:
      - id: pyright

  - repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
      - id: djhtml
        args:
          - --tabwidth=4

  - repo: https://github.com/thibaudcolas/curlylint
    rev: "v0.13.1"
    hooks:
      - id: curlylint
