name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Django 3.2
          - django-version: "3.2.0"
            python-version: "3.8"
          - django-version: "3.2.0"
            python-version: "3.9"
          - django-version: "3.2.0"
            python-version: "3.10"
          # Django 4.0
          - django-version: "4.0.0"
            python-version: "3.8"
          - django-version: "4.0.0"
            python-version: "3.9"
          - django-version: "4.0.0"
            python-version: "3.10"
          - django-version: "4.0.0"
            python-version: "3.11-dev"
          # Django 4.1
          - django-version: "4.1.0"
            python-version: "3.8"
          - django-version: "4.1.0"
            python-version: "3.9"
          - django-version: "4.1.0"
            python-version: "3.10"
          - django-version: "4.1.0"
            python-version: "3.11-dev"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Run tests
        run: |
          poetry run pip install django~=${{ matrix.django-version }}
          poetry run pytest
