name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          cache: true
          cache-dependency-path: "**/pdm.lock"

      - name: Install Dependencies
        run: pdm install

      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          pdm config repository.pypi.username "__token__"
          pdm config repository.pypi.password $PYPI_TOKEN
          pdm publish
