name: Publish documentation

on:
  release:
    types:
      - published

jobs:
  publish_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install poetry
        uses: abatilo/actions-poetry@v3

      - name: Install dependencies
        run: poetry install

      - name: Build documentation
        run: poetry run mkdocs build

      - name: Publish documentation
        run: poetry run mkdocs gh-deploy --force
